site_name: GPT Training
repo_url: https://github.com/nakamasato/gpt-training/

theme:
  name: material
  features:
    - header.autohide
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.instant # clicks on all internal links will be intercepted and dispatched via XHR without fully reloading the page.
    - toc.follow # the sidebar is automatically scrolled so that the active anchor is always visible.
    - navigation.tracking # the URL in the address bar is automatically updated with the active anchor as highlighted in the table of contents
    - navigation.top
    - content.code.copy
    - content.code.select

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
  - admonition
  - pymdownx.details

nav:
  - 'Getting Started': index.md
  - ...
  - references.md

extra:
  analytics:
    provider: google
    property: G-9NTB93RVPJ
