[tool.poetry]
name = "gpt-training"
version = "0.1.0"
description = "GPT Training"
authors = ["Masato Naka <masatonaka1989@gmail.com>"]
readme = "README.md"
packages = [{include = "gpt_training"}]

[tool.poetry.dependencies]
python = "3.11"
mkdocs-material = "^9.5.3"
open-interpreter = "^0.2.0"
streamlit = "^1.30.0"
openai = "^1.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
