name: github-pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - labeled
      - closed
      - opened # default
      - synchronize # default
      - reopened # default
    paths:
      - 'docs/**'
      - '.github/workflows/github-pages.yml'
      - 'mkdocs.yml'

permissions:
  contents: write
jobs:
  deploy:
    if: contains( github.event.pull_request.labels.*.name, 'github-pages') || github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          pip install mkdocs-material mkdocs-awesome-pages-plugin
      - run: mkdocs gh-deploy --force
